### ISSUE TITLE
code/spring-distributed-tracing-end does not have date-service-end

### ISSUE THREAD

**Issue by ElDavoo** [nbicocchi/learn-microservices#1]
In the [docker-compose file](https://github.com/nbicocchi/learn-microservices/blob/c9dc2b5e832bfdf872fe54138ad19570e19fd733/code/spring-distributed-tracing-end/docker-compose.yml#L28C12-L28C28) of `spring-distributed-tracing-end` , a non-existent `date-service-end` service is mentioned.

**Comment by nbicocchi** [comment]
I know. The very last lessons are not ready yet. Thank you :)

**Comment by nbicocchi** [comment]
Solved

**Comment by nbicocchi** [comment]
Solved
